export const workspaceRoutes = [
  {
    key: 'dashboard',
    label: '控制台',
    path: '/dashboard',
  },
  {
    key: 'petCreate',
    label: '创建宠物',
    path: '/pets/create',
  },
  {
    key: 'petPublicQuery',
    label: '公开宠物查询',
    path: '/pets/public-query',
  },
  {
    key: 'petRelations',
    label: '宠物绑定',
    path: '/pets/relations',
  },
]

export const relationModules = [
  {
    key: 'rances',
    label: '种族绑定',
    endpointSegment: 'rances',
    collectionKey: 'rances',
    itemIdKey: 'rance_id',
    itemNameKey: 'rance_name',
    createKey: 'rance_id',
    replaceKey: 'new_rance_id',
    optionsKey: 'rances',
  },
  {
    key: 'egg-groups',
    label: '蛋组绑定',
    endpointSegment: 'egg-groups',
    collectionKey: 'egg_groups',
    itemIdKey: 'egg_group_id',
    itemNameKey: 'egg_group_name',
    createKey: 'egg_group_id',
    replaceKey: 'new_egg_group_id',
    optionsKey: 'eggGroups',
  },
  {
    key: 'generations',
    label: '世代绑定',
    endpointSegment: 'generations',
    collectionKey: 'generations',
    itemIdKey: 'generation_id',
    itemNameKey: 'generation_name',
    createKey: 'generation_id',
    replaceKey: 'new_generation_id',
    optionsKey: 'generations',
  },
]

export const adminModules = [
  {
    key: 'tags',
    routeKey: 'tags',
    group: '基础资料',
    label: '标签',
    endpoint: '/admin/tags/',
    description: '维护宠物标签名称与颜色。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'color', label: '颜色' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      { key: 'name', label: '标签名', type: 'text', required: true },
      { key: 'color', label: '颜色', type: 'color', default: '#f97316' },
    ],
    tips: ['标签已支持删除；如果标签已经绑定宠物，后端会拒绝删除。'],
  },
  {
    key: 'rances',
    routeKey: 'rances',
    group: '宠物资料',
    label: '种族',
    endpoint: '/admin/rances/',
    description: '维护种族基础属性，后端删除逻辑为软删除。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'p_id', label: '来源ID' },
      { key: 'name', label: '名称' },
      { key: 'total', label: '总和' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      { key: 'p_id', label: '来源ID', type: 'number', emptyAsNull: true },
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'hp', label: 'HP', type: 'number', required: true },
      { key: 'attack', label: '攻击', type: 'number', required: true },
      { key: 'defense', label: '防御', type: 'number', required: true },
      { key: 'special_attack', label: '特攻', type: 'number', required: true },
      { key: 'special_defense', label: '特防', type: 'number', required: true },
      { key: 'speed', label: '速度', type: 'number', required: true },
      { key: 'total', label: '总和', type: 'number', required: true },
    ],
  },
  {
    key: 'features',
    routeKey: 'features',
    group: '宠物资料',
    label: '特性',
    endpoint: '/admin/features/',
    description: '维护特性简介与详情。',
    canDelete: true,
    listQueryKey: 'name',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'introduction', label: '简介' },
      { key: 'detail', label: '详情' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      { key: 'introduction', label: '简介', type: 'text', required: true },
      { key: 'detail', label: '详情', type: 'textarea', rows: 5 },
    ],
  },
  {
    key: 'generations',
    routeKey: 'generations',
    group: '宠物资料',
    label: '世代',
    endpoint: '/admin/generations/',
    description: '维护世代名称。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [{ key: 'name', label: '名称', type: 'text', required: true }],
  },
  {
    key: 'eggGroups',
    routeKey: 'egg-groups',
    group: '宠物资料',
    label: '蛋组',
    endpoint: '/admin/egg-groups/',
    description: '维护宠物蛋组。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [{ key: 'name', label: '名称', type: 'text', required: true }],
  },
  {
    key: 'skillCategories',
    routeKey: 'skill-categories',
    group: '战斗资料',
    label: '技能分类',
    endpoint: '/admin/skill-categories/',
    description: '维护技能分类。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [{ key: 'name', label: '名称', type: 'text', required: true }],
  },
  {
    key: 'skills',
    routeKey: 'skills',
    group: '战斗资料',
    label: '技能',
    endpoint: '/admin/skills/',
    description: '维护技能学习方式、分类与战斗属性。',
    canDelete: true,
    lookupDeps: ['skillCategories'],
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '技能名' },
      { key: 'category_id', label: '分类ID' },
      { key: 'attribute_id', label: '属性ID' },
      { key: 'damage', label: '伤害' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      { key: 'learn_type', label: '学习类型', type: 'number', emptyAsNull: true },
      {
        key: 'category_id',
        label: '技能分类',
        type: 'select',
        emptyAsNull: true,
        optionsFrom: 'skillCategories',
        optionLabelKey: 'name',
      },
      { key: 'attribute_id', label: '属性ID', type: 'number', emptyAsNull: true },
      { key: 'name', label: '技能名', type: 'text', required: true },
      { key: 'introduction', label: '简介', type: 'text' },
      { key: 'detail', label: '详情', type: 'textarea', rows: 5 },
      { key: 'damage', label: '伤害', type: 'number', emptyAsNull: true },
      { key: 'aim', label: '命中', type: 'number', emptyAsNull: true },
      { key: 'pp', label: 'PP', type: 'number', emptyAsNull: true },
      { key: 'cost_time', label: '耗时', type: 'number', emptyAsNull: true },
    ],
  },
  {
    key: 'itemCategories',
    routeKey: 'item-categories',
    group: '物品资料',
    label: '物品分类',
    endpoint: '/admin/item-categories/',
    description: '维护物品分类。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [{ key: 'name', label: '名称', type: 'text', required: true }],
  },
  {
    key: 'items',
    routeKey: 'items',
    group: '物品资料',
    label: '物品',
    endpoint: '/admin/items/',
    description: '维护物品多语言名称与说明。',
    canDelete: true,
    lookupDeps: ['itemCategories'],
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'jp_name', label: '日文名' },
      { key: 'en_name', label: '英文名' },
      { key: 'categories', label: '分类' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'jp_name', label: '日文名', type: 'text' },
      { key: 'en_name', label: '英文名', type: 'text' },
      { key: 'introduction', label: '简介', type: 'text' },
      { key: 'detail', label: '详情', type: 'textarea', rows: 5 },
    ],
  },
  {
    key: 'gameDocs',
    routeKey: 'game-docs',
    group: '内容管理',
    label: '游戏文档',
    endpoint: '/admin/game-docs/',
    description: '维护二级游戏文档目录与 Markdown 内容。',
    canDelete: true,
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'p_id', label: '父级ID' },
      { key: 'name', label: '标题' },
      { key: 'path', label: '路径' },
      { key: 'modified_at', label: '更新时间' },
    ],
    fields: [
      {
        key: 'p_id',
        label: '父级文档组',
        type: 'select',
        default: 0,
        emptyAsNull: true,
        optionsFrom: 'documentGroups',
        optionLabelKey: 'name',
      },
      { key: 'name', label: '标题', type: 'text', required: true },
      { key: 'path', label: '路径', type: 'text' },
      {
        key: 'content',
        label: 'Markdown 内容',
        type: 'textarea',
        rows: 12,
        preserveWhitespace: true,
        emptyAsNull: true,
      },
    ],
    tips: ['父级为空时表示顶级文档组，顶级文档组不会保存正文内容。'],
  },
]

export const adminModuleMap = Object.fromEntries(adminModules.map((module) => [module.key, module]))
const adminModuleRouteMap = Object.fromEntries(adminModules.map((module) => [module.routeKey, module]))

export function getModuleByRouteKey(routeKey) {
  return adminModuleRouteMap[routeKey] || null
}
